# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Introduction to the History of the United States
email: c.blevins@northeastern.edu
description: > # this means to ignore newlines until "baseurl:"
  Northeastern University, Fall 2018
baseurl: "/f18-intro-us" # the subpath of your site, e.g. /blog
url: "https://cblevins.github.io" # the base hostname & protocol for your site
#twitter_username: historying
#github_username:  cblevins
university: "Northeastern University"
course_number: "HIST 1130"
semester: "Fall 2018"
room: "Snell Engineering Center, Room 108"
meetingtime: "Mon/Wed/Thurs 9:15-10:20"

instructor: Cameron Blevins
email: c.blevins@northeastern.edu
office: "237 Meserve Hall"
officehours: "By Appointment"

copyright: "[Cameron Blevins](http://cameronblevins.org)<br>
Northeastern University<br>
Fall 2018<br><br>
Made with Jekyll using the [So Simple](https://github.com/mmistakes/so-simple-theme/) theme."

logo: "/images/36-star-flag-small-crop.png"

# Build settings
markdown: kramdown
#theme: minima
#theme: jekyll-theme-hacker
remote_theme: "mmistakes/so-simple-theme"
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
